class LocalizedStrings:
    def __init__(self):
        self.strings = {
            "FORMAT_DATE": "d/M/yyyy",
            "FORMAT_DATETIME": "d/M/yyyy hh:mm",
            "TITLE_PROJECT": "QUẢN LÝ QUÁN CÀ PHÊ",
            "MANAGE_X": "quản lý {0}",
            "CATEGORY": "Loại Sản Phẩm",
            "PRODUCT": "Sản Phẩm",
            "ORDER": "Đơn Hàng",
            "INVOICE": "Hóa Đơn",
            "CUSTOMER": "Khách Hàng",
            "TOTAL_AMOUNT": "Thành tiền",
            "ENTER_YOUR_SELECTION": "Nhập lựa chọn của bạn: ",
            "DISPLAY_LIST_X": "Hiển thị danh sách {0}",
            "INPUT_X": "Nhập {0}: ",
            "ADD_X": "Thêm {0}",
            "UPDATE_X": "Chỉnh sửa {0}",
            "DELETE_X": "Xóa {0}",
            "FIND_X": "Tìm kiếm {0}",
            "ID": "mã",
            "BACK": "Quay lại",
            "X_HAS_BEEN_ADDED_SUCCESSFULLY": "{0} đã được thêm thành công.",
            "ENTER_THE_ID_OF_X_TO_ADD": "Nhập ID của {0} mới: ",
            "ENTER_THE_ID_OF_X_TO_UPDATE": "Nhập ID của {0} cần cập nhật: ",
            "ENTER_THE_ID_OF_X_TO_DELETE": "Nhập ID của {0} cần xoá: ",
            "ENTER_THE_INFORMATION_OF_X_TO_ADD": "Nhập thông tin của {0} mới: ",
            "ENTER_THE_INFORMATION_OF_X_TO_UPDATE": "Thông tin của {0} cần cập nhật: ",
            "ENTER_THE_INFORMATION_OF_X_TO_DELETE": "Thông tin của {0} cần xoá: ",
            "ENTER_THE_KEY_ENTER_TO_RETURN_TO_THE_MENU": "Nhập phím [enter] để trở về menu",
            "CHOOSE_AN_OPTION": "Chọn một tùy chọn: ",
            "MESSAGE_INVALID_OPTION": "Tùy chọn không hợp lệ. Vui lòng chọn lại!",
            "INPUT_NAME_OF_X_NEW": "Nhập tên {0} mới: ",
            "INPUT_NAME_OF_X": "Nhập tên {0}: ",
            "X_WITH_THE_ENTERED_ID_WAS_NOT_FOUND": "Không tìm thấy {0} với ID đã nhập!",
            "X_NOT_FOUND": "Không tìm thấy {0}!",
            "CANNOT_DELETE_X_ASSOCIATED_Y": "Không thể xóa {0} vì nó có {1} liên quan.",
            "LIST_X": "Danh sách {0}.",
            "X_HAS_BEEN_DELETE": "{0} đã được xóa",
            "X_HAS_BEEN_UPDATE": "{0} đã được cập nhật",
            "INPUT_X_NEW": "Nhập {0} mới",
            "ADD_X_NEW": "Thêm {0} mới",
            "NAME": "tên",
            "BIRTHDAY": "ngày sinh",
            "PHONENUMBER": "số điện thoại",
            "EMAIL": "email",
            "POINT": "điểm",
            "SELECT_INFORMATION_TO_UPDATE": "Lựa chọn thông tin cần cập nhật: ",
            "THERE_ARE_NO_X_IN_THE_LIST": "Không có {0} nào trong danh sách",
            "X_IS_EXIST_IN_LIST": "{0} đã tồn tại trong danh sách",
        }

    def get_localized_string(self, locale, key):
        return self.strings.get(locale, {}).get(key, f"String not found for key: {key}")
